services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice_shop
    ports:
      - "3000:3000"
    restart: always

  threat-dragon:
    image: owasp/threat-dragon:stable
    container_name: threat_dragon
    ports:
      - "8080:3000"
    volumes:
      - "C:\\Users\\Jos√© Silva\\Desktop\\Pl3_LC\\juice-shop\\threat-dragon\\config.env:/app/.env"
    restart: always